# Generated by Django 6.1.2 on 2026-10-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_baths_listing_bedrooms_listing_beds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='is_guest_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='accuracy',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='review',
            name='location_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='review',
            name='value_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
