# Generated by Django 6.1.2 on 2026-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_options_alter_listingimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
